stages:
  - test

include:
  - component: $CI_SERVER_FQDN/fsrvcorp/ci-components/golang@0.1.0
    inputs:
      stage: test
  - component: $CI_SERVER_FQDN/fsrvcorp/ci-components/semver@0.1.0
    inputs:
      prefix: v
