stages:
  - test
  - release
.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
variables:
  SEMVER_PREFIX: v
include:
  - { project: fsrvcorp/templates, file: templates/language/go.yml, ref: 1.0.12 }
  - { project: fsrvcorp/templates, file: templates/release/semver.yml, ref: 1.0.12 }
